export const US_CITIES: string[] = [
  "Albuquerque, NM",
  "Annapolis, MD",
  "Atlanta, GA",
  "Augusta, ME",
  "Austin, TX",
  "Bakersfield, CA",
  "Baltimore, MD",
  "Baton Rouge, LA",
  "Birmingham, AL",
  "Bismarck, ND",
  "Boise, ID",
  "Boston, MA",
  "Buffalo, NY",
  "Burlington, VT",
  "Carson City, NV",
  "Charleston, SC",
  "Charleston, WV",
  "Charlotte, NC",
  "Cheyenne, WY",
  "Chicago, IL",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbia, SC",
  "Columbus, OH",
  "Concord, NH",
  "Dallas, TX",
  "Denver, CO",
  "Des Moines, IA",
  "Detroit, MI",
  "Dover, DE",
  "El Paso, TX",
  "Fargo, ND",
  "Frankfort, KY",
  "Harrisburg, PA",
  "Hartford, CT",
  "Helena, MT",
  "Honolulu, HI",
  "Houston, TX",
  "Indianapolis, IN",
  "Jackson, MS",
  "Jacksonville, FL",
  "Jefferson City, MO",
  "Juneau, AK",
  "Kansas City, MO",
  "Lansing, MI",
  "Las Vegas, NV",
  "Lincoln, NE",
  "Little Rock, AR",
  "Los Angeles, CA",
  "Louisville, KY",
  "Madison, WI",
  "Manchester, NH",
  "Memphis, TN",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Mobile, AL",
  "Montgomery, AL",
  "Montpelier, VT",
  "Nashville, TN",
  "New Orleans, LA",
  "New York, NY",
  "Newark, NJ",
  "Oklahoma City, OK",
  "Olympia, WA",
  "Omaha, NE",
  "Orlando, FL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pierre, SD",
  "Pittsburgh, PA",
  "Portland, ME",
  "Portland, OR",
  "Providence, RI",
  "Raleigh, NC",
  "Reno, NV",
  "Richmond, VA",
  "Sacramento, CA",
  "Saint Louis, MO",
  "Saint Paul, MN",
  "Salem, OR",
  "Salt Lake City, UT",
  "San Antonio, TX",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Santa Fe, NM",
  "Seattle, WA",
  "Sioux Falls, SD",
  "Spokane, WA",
  "Springfield, IL",
  "Tallahassee, FL",
  "Tampa, FL",
  "Topeka, KS",
  "Trenton, NJ",
  "Tucson, AZ",
  "Tulsa, OK",
  "Virginia Beach, VA",
  "Washington, DC",
  "Wichita, KS",
];
